name: generate animation  # ワークフローの名前を設定します。

on:
  # 自動的に毎日24時間ごとに実行されるスケジュールを設定します。
  schedule:
    - cron: "0 */24 * * *"  # 毎日実行されます。
  
  # 手動でいつでもジョブを実行できるようにします。
  workflow_dispatch:
  
  # メインブランチにプッシュされたときに実行されるように設定します。
  push:
    branches:
    - main  # 'main' ブランチにプッシュされた場合に実行されます。

jobs:
  generate:  # 'generate' という名前のジョブを定義します。
    runs-on: ubuntu-latest  # Ubuntuの最新バージョンで実行します。
    timeout-minutes: 10  # ジョブの最大実行時間を10分に設定します。
    
    steps:
      # GitHubユーザーの貢献グラフからスネークゲームを生成し、SVGアニメーションを出力します。
      - name: generate github-contribution-grid-snake.svg  # ステップの名前
        uses: Platane/snk/svg-only@v3  # Platane/snkリポジトリのアクションを使用します。
        with:
          github_user_name: Saaatsuki  # 対象のGitHubユーザー名を指定します。
          outputs: |  # 出力ファイルの指定
            dist/github-contribution-grid-snake.svg  # 通常のスネークSVG
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark  # ダークモードのスネークSVG
            dist/saaatsuki-custom.svg?palette=github-dark&color_snake=#FE8019&color_dots=#E1E1E1,#F0E68C,#ADFF2F,#7FFF00,#32CD32,#228B22,#006400  # カスタムスネークSVGと色の設定

      # distディレクトリ内の生成物を特定のブランチにプッシュします。
      - name: push github-contribution-grid-snake.svg to the output branch  # ステップの名前
        uses: crazy-max/ghaction-github-pages@v3.1.0  # GitHub Pagesにデプロイするアクションを使用します。
        with:
          target_branch: output  # 出力先のブランチを指定します。
          build_dir: dist  # プッシュするディレクトリを指定します。
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHubトークンを環境変数として設定します。
